/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2019-04-14 10:29:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateRedVoznjeJSP_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1532767410426L));
    _jspx_dependants.put("jar:file:/D:/autobuskaStanica-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/AutobuskaStanicaWEB/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Create red voznje</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* BASIC */\r\n");
      out.write("body {\r\n");
      out.write("\t/* \tbackground-image: */\r\n");
      out.write("\t/* \t\turl(\"https://stil.kurir.rs/data/images/2017/06/30/20/120607_pica_ls.jpg\"); */\r\n");
      out.write("\t/* \tbackground-repeat: no-repeat; */\r\n");
      out.write("\tbackground-color: grey;\r\n");
      out.write("\tbackground-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custab {\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin: 5% 0;\r\n");
      out.write("\tbox-shadow: 3px 3px 2px #ccc;\r\n");
      out.write("\ttransition: 0.5s;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custab:hover {\r\n");
      out.write("\tbox-shadow: 3px 3px 0px transparent;\r\n");
      out.write("\ttransition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thead {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p.message {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-family: Ariel;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont: ariel;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pad {\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Autobuska stanica WEB</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/AutobuskaStanicaWEB/Main\" method=\"get\">HOME</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/AutobuskaStanicaWEB/LoginSERVLET\" method=\"get\">LOGIN</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/AutobuskaStanicaWEB/RegistrationSERVLET\"\r\n");
      out.write("\t\t\t\t\tmethod=\"get\">SIGNUP</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/AutobuskaStanicaWEB/Coment\" method=\"get\">COMENT</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/AutobuskaStanicaWEB/Contact\" method=\"get\">CONTACT</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Container (Login Section) -->\r\n");
      out.write("\t<div class=\"wrapper fadeInDown\">\r\n");
      out.write("\t\t<div id=\"formContent\">\r\n");
      out.write("\t\t\t<!-- Tabs Titles -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Icon -->\r\n");
      out.write("\t\t\t<div class=\"fadeIn first\">\r\n");
      out.write("\t\t\t\t<h3>Create red voznje</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Login Form -->\r\n");
      out.write("\t\t\t<form class=\"pad\" action=\"/AutobuskaStanicaWEB/CreateRedVoznje2SERVLET\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"idVoznje\" class=\"fadeIn second\"\r\n");
      out.write("\t\t\t\t\tname=\"idVoznje\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idVoznje }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\tPolazak: \r\n");
      out.write("\t\t\t\t\t<input type=\"time\" id=\"polazakVreme\"\r\n");
      out.write("\t\t\t\t\tclass=\"fadeIn second\" name=\"polazakVreme\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"polazakVreme\" /><br>\r\n");
      out.write("\t\t\t\t\tDolazak: <input type=\"time\"\r\n");
      out.write("\t\t\t\t\tid=\"dolazakVreme\" class=\"fadeIn second\" name=\"dolazakVreme\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"dolazakVreme\" /><br><br>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<input type=\"radio\"\r\n");
      out.write("\t\t\t\t\tname=\"deoNedelje\" value=\"radniDan\"> Radni dan <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"deoNedelje\" value=\"subota\"> Subota <input\r\n");
      out.write("\t\t\t\t\ttype=\"radio\" name=\"deoNedelje\" value=\"nedelja\"> Nedelja <input\r\n");
      out.write("\t\t\t\t\ttype=\"submit\" class=\"fadeIn fourth\" value=\"CreateRedVoznje\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
